package chat;

import java.awt.event.KeyEvent;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author hashi
 */
public class chat_client extends javax.swing.JFrame {

    static Client cliente;
    static Login login;
    static Thread thread_client;
    public static String ip;
    public static int port;
    public static String user;

    /**
     * Creates new form chat_client
     */
    public chat_client(String IP, int Port, String User) {
        initComponents();
        Pane.setLayout(new MigLayout("fillx"));
        ip = IP;
        port = Port;
        user = User;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msg_textt = new javax.swing.JTextField();
        msg_send = new javax.swing.JButton();
        Go_Back = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Pane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Client");
        setMinimumSize(new java.awt.Dimension(432, 323));

        msg_textt.setForeground(new java.awt.Color(1, 1, 1));
        msg_textt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                msg_texttKeyPressed(evt);
            }
        });

        msg_send.setText("send");
        msg_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msg_sendActionPerformed(evt);
            }
        });

        Go_Back.setText("Go Back");
        Go_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Go_BackActionPerformed(evt);
            }
        });

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setAutoscrolls(true);

        Pane.setAutoscrolls(true);

        javax.swing.GroupLayout PaneLayout = new javax.swing.GroupLayout(Pane);
        Pane.setLayout(PaneLayout);
        PaneLayout.setHorizontalGroup(
            PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );
        PaneLayout.setVerticalGroup(
            PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(Pane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(msg_textt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(msg_send, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2)
                    .addComponent(Go_Back))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Go_Back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(msg_textt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(msg_send, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        jScrollPane2.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void msg_texttKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_msg_texttKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cliente.envia = true;
        }    }//GEN-LAST:event_msg_texttKeyPressed

    private void Go_BackActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Go_BackActionPerformed
        
        if(cliente.close != true){
            cliente.output.println("<CLOSE>");
        }
        login = new Login();
        login.show();
        thread_client.interrupt();
        dispose();
    }// GEN-LAST:event_Go_BackActionPerformed

    private void msg_sendActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_msg_sendActionPerformed
        cliente.envia = true;
    }// GEN-LAST:event_msg_sendActionPerformed



    /**
     * @param args the command line arguments
     */
    public void Executa() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                setVisible(true);
                try {
                    cliente = new Client(ip, port, user);
                    thread_client = new Thread(cliente);
                    thread_client.start();
                } catch (Exception e) {
                }

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Go_Back;
    public static javax.swing.JPanel Pane;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JButton msg_send;
    public static javax.swing.JTextField msg_textt;
    // End of variables declaration//GEN-END:variables

}
